### ISSUE TITLE
Problema di Accesso ai Dati SIRI

### ISSUE THREAD

**Issue by Giasinit** [5Tsrl/siri-italian-profile#1]
Salve a tutti,

Ho preso visione del progetto **MAAS4ITALY** e dei tempi previsti per rendere disponibili il NeTEx e il SIRI. So che diversi RAP hanno trasmesso i dati del NeTEx al NAP ([National Access Point Italiano](https://nap-1926.it/nap/mmtis/public/static/multimodal)), ma non del SIRI. Un esempio è la [Regione del Veneto](https://nap-1926.it/nap/mmtis/public/catalog/Organisation/51113), che nel documento [Allegato 3](https://bur.regione.veneto.it/BurvServices/Pubblica/Download.aspx?name=101_Allegato_A3_DDR_101_14-02-2024_523567.pdf&type=7&storico=False) - **Piano Operativo “MaaS4Veneto”** alla pagina 32, indica che la data prevista per la disponibilità dei dati dinamici (SIRI) sulla piattaforma nazionale per tutti gli operatori era il 30/04/2024, ma non risultano ancora disponibili sul NAP.

Ho anticipato la mia ricerca e ho individuato l'endpoint per il SIRI relativo all'operatore che mi interessa particolarmente, BUSITALIA VENETO S.p.A. È il seguente: https://siri-biv.fsbusitalia.com/VMWS/VMService.svc. 

Ho consultato le vostre linee guida e la documentazione dello standard, ma non riesco a capire come posso recuperare i dati dei veicoli e delle loro posizioni, poiché all'indirizzo https://siri-biv.fsbusitalia.com/VMWS/VMService.svc?wsdl non trovo nulla.

Grazie per il vostro aiuto.

**Comment by Giasinit** [comment]
Alla fine ci sono riuscito con SoapUI.
Però comunque sono solo forniti al massimo 20 bus in tempo reale, la cui maggioranza in deposito..

-- Aggiornamento Novembre24
Il SIRI proposto dal mio operatore di TPL(BUSITALIA VENETO S.p.A.) è formato solo dai nuovi bus elettrici, infatti il SIRI servirebbe per tener conto di quanta percentuale di carica rimasta

**Comment by Giasinit** [comment]
Buongiorno, chiedo scusa ancora per il disturbo, ma non tornano i conti.. i dati SIRI non ci sono ancora sul NAP, ma i NeTEx si.. perché non ci sono?

**Comment by fabiogdb** [comment]
Buongiorno, per il momento il NAP riceve solamente i dati statici dai RAP di diverse regioni per questo motivo sono disponibili solo i NeTEx; per quanto riguarda i dati dinamici (SIRI) si sta ancora lavorando sia a livello regionale che nazionale e quindi non sono ancora disponibili dati

**Comment by Giasinit** [comment]
La ringrazio della risposta, sembrerà stupido.. ma non ci sono così grandi differenze con il GTFS-RT in confronto a SIRI.

**Comment by Giasinit** [comment]
Chiudo l'issue come risolto.
È bastato inviare una richiesta di accesso civico generalizzato all'azienda, aspettare circa un mese e, se tutto va bene, la richiesta viene accolta e ricevi le informazioni.
Lo dico a chi si trova in una situazione simile alla mia.
